/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.gbif.pipelines.core.functions.interpretation.error;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum IssueType { 
  OTHERS, PARSE_ERROR, DAY_OUT_OF_RANGE, MONTH_OUT_OF_RANGE, INVALID_YEAR, COUNTRY_AND_COUNTRYCODE_DONOT_MATCH  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"IssueType\",\"namespace\":\"org.gbif.pipelines.core.functions.interpretation.error\",\"symbols\":[\"OTHERS\",\"PARSE_ERROR\",\"DAY_OUT_OF_RANGE\",\"MONTH_OUT_OF_RANGE\",\"INVALID_YEAR\",\"COUNTRY_AND_COUNTRYCODE_DONOT_MATCH\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
