/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.gbif.pipelines.core.functions.interpretation.error;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum LineageType { 
  OTHERS, SET_TO_NULL, SET_COUNTRYCODE_FROM_COUNTRY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LineageType\",\"namespace\":\"org.gbif.pipelines.core.functions.interpretation.error\",\"symbols\":[\"OTHERS\",\"SET_TO_NULL\",\"SET_COUNTRYCODE_FROM_COUNTRY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
