/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.gbif.pipelines.core.functions.interpretation.error;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Lineage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Lineage\",\"namespace\":\"org.gbif.pipelines.core.functions.interpretation.error\",\"fields\":[{\"name\":\"remark\",\"type\":\"string\"},{\"name\":\"lineageType\",\"type\":{\"type\":\"enum\",\"name\":\"LineageType\",\"symbols\":[\"OTHERS\",\"SET_TO_NULL\",\"SET_COUNTRYCODE_FROM_COUNTRY\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence remark;
  @Deprecated public org.gbif.pipelines.core.functions.interpretation.error.LineageType lineageType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Lineage() {}

  /**
   * All-args constructor.
   */
  public Lineage(java.lang.CharSequence remark, org.gbif.pipelines.core.functions.interpretation.error.LineageType lineageType) {
    this.remark = remark;
    this.lineageType = lineageType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return remark;
    case 1: return lineageType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: remark = (java.lang.CharSequence)value$; break;
    case 1: lineageType = (org.gbif.pipelines.core.functions.interpretation.error.LineageType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'remark' field.
   */
  public java.lang.CharSequence getRemark() {
    return remark;
  }

  /**
   * Sets the value of the 'remark' field.
   * @param value the value to set.
   */
  public void setRemark(java.lang.CharSequence value) {
    this.remark = value;
  }

  /**
   * Gets the value of the 'lineageType' field.
   */
  public org.gbif.pipelines.core.functions.interpretation.error.LineageType getLineageType() {
    return lineageType;
  }

  /**
   * Sets the value of the 'lineageType' field.
   * @param value the value to set.
   */
  public void setLineageType(org.gbif.pipelines.core.functions.interpretation.error.LineageType value) {
    this.lineageType = value;
  }

  /** Creates a new Lineage RecordBuilder */
  public static org.gbif.pipelines.core.functions.interpretation.error.Lineage.Builder newBuilder() {
    return new org.gbif.pipelines.core.functions.interpretation.error.Lineage.Builder();
  }
  
  /** Creates a new Lineage RecordBuilder by copying an existing Builder */
  public static org.gbif.pipelines.core.functions.interpretation.error.Lineage.Builder newBuilder(org.gbif.pipelines.core.functions.interpretation.error.Lineage.Builder other) {
    return new org.gbif.pipelines.core.functions.interpretation.error.Lineage.Builder(other);
  }
  
  /** Creates a new Lineage RecordBuilder by copying an existing Lineage instance */
  public static org.gbif.pipelines.core.functions.interpretation.error.Lineage.Builder newBuilder(org.gbif.pipelines.core.functions.interpretation.error.Lineage other) {
    return new org.gbif.pipelines.core.functions.interpretation.error.Lineage.Builder(other);
  }
  
  /**
   * RecordBuilder for Lineage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Lineage>
    implements org.apache.avro.data.RecordBuilder<Lineage> {

    private java.lang.CharSequence remark;
    private org.gbif.pipelines.core.functions.interpretation.error.LineageType lineageType;

    /** Creates a new Builder */
    private Builder() {
      super(org.gbif.pipelines.core.functions.interpretation.error.Lineage.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.gbif.pipelines.core.functions.interpretation.error.Lineage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.remark)) {
        this.remark = data().deepCopy(fields()[0].schema(), other.remark);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lineageType)) {
        this.lineageType = data().deepCopy(fields()[1].schema(), other.lineageType);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Lineage instance */
    private Builder(org.gbif.pipelines.core.functions.interpretation.error.Lineage other) {
            super(org.gbif.pipelines.core.functions.interpretation.error.Lineage.SCHEMA$);
      if (isValidValue(fields()[0], other.remark)) {
        this.remark = data().deepCopy(fields()[0].schema(), other.remark);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lineageType)) {
        this.lineageType = data().deepCopy(fields()[1].schema(), other.lineageType);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'remark' field */
    public java.lang.CharSequence getRemark() {
      return remark;
    }
    
    /** Sets the value of the 'remark' field */
    public org.gbif.pipelines.core.functions.interpretation.error.Lineage.Builder setRemark(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.remark = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'remark' field has been set */
    public boolean hasRemark() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'remark' field */
    public org.gbif.pipelines.core.functions.interpretation.error.Lineage.Builder clearRemark() {
      remark = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'lineageType' field */
    public org.gbif.pipelines.core.functions.interpretation.error.LineageType getLineageType() {
      return lineageType;
    }
    
    /** Sets the value of the 'lineageType' field */
    public org.gbif.pipelines.core.functions.interpretation.error.Lineage.Builder setLineageType(org.gbif.pipelines.core.functions.interpretation.error.LineageType value) {
      validate(fields()[1], value);
      this.lineageType = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'lineageType' field has been set */
    public boolean hasLineageType() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'lineageType' field */
    public org.gbif.pipelines.core.functions.interpretation.error.Lineage.Builder clearLineageType() {
      lineageType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Lineage build() {
      try {
        Lineage record = new Lineage();
        record.remark = fieldSetFlags()[0] ? this.remark : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.lineageType = fieldSetFlags()[1] ? this.lineageType : (org.gbif.pipelines.core.functions.interpretation.error.LineageType) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
