package org.gbif.pipelines.maven;

import static java.nio.charset.StandardCharsets.UTF_8;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import lombok.Setter;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.gbif.occurrence.download.hive.EventAvroHdfsTableDefinition;
import org.gbif.occurrence.download.hive.OccurrenceAvroHdfsTableDefinition;

@Mojo(name = "avroschemageneration", defaultPhase = LifecyclePhase.GENERATE_SOURCES)
@Setter
public class OccurrenceAvscGeneratorMojo extends AbstractMojo {

  @Parameter(property = "avroschemageneration.pathToWrite")
  private String pathToWrite;

  @Parameter(property = "avroschemageneration.occurrenceFile")
  private String occurrenceFile;

  @Parameter(property = "avroschemageneration.eventFile")
  private String eventFile;

  @Override
  public void execute() throws MojoExecutionException {

    var occurrencePath = Paths.get(pathToWrite, occurrenceFile);
    var occurrenceSchema = OccurrenceAvroHdfsTableDefinition.avroDefinition();

    getLog().info("Create occurrence avro schema - " + occurrencePath);
    try {
      var header =
          "/** Autogenerated by maven-occurrence-avsc-schema-generator. DO NOT EDIT DIRECTLY */\n";
      var body = occurrenceSchema.toString(true);
      var result = header + body;

      Files.write(occurrencePath, result.getBytes(UTF_8));
    } catch (IOException ex) {
      throw new MojoExecutionException(ex);
    }

    var eventPath = Paths.get(pathToWrite, eventFile);
    var eventSchema = EventAvroHdfsTableDefinition.avroDefinition();
    getLog().info("Create event avro schema - " + eventPath);
    try {
      var header =
          "/** Autogenerated by maven-occurrence-avsc-schema-generator. DO NOT EDIT DIRECTLY */\n";
      var body = eventSchema.toString(true);
      var result = header + body;

      Files.write(eventPath, result.getBytes(UTF_8));
    } catch (IOException ex) {
      throw new MojoExecutionException(ex);
    }
  }
}
