/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.gbif.pipelines.io.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Validation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Validation\",\"namespace\":\"org.gbif.pipelines.io.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"severity\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence severity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Validation() {}

  /**
   * All-args constructor.
   */
  public Validation(java.lang.CharSequence name, java.lang.CharSequence severity) {
    this.name = name;
    this.severity = severity;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return severity;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: severity = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'severity' field.
   */
  public java.lang.CharSequence getSeverity() {
    return severity;
  }

  /**
   * Sets the value of the 'severity' field.
   * @param value the value to set.
   */
  public void setSeverity(java.lang.CharSequence value) {
    this.severity = value;
  }

  /** Creates a new Validation RecordBuilder */
  public static org.gbif.pipelines.io.avro.Validation.Builder newBuilder() {
    return new org.gbif.pipelines.io.avro.Validation.Builder();
  }
  
  /** Creates a new Validation RecordBuilder by copying an existing Builder */
  public static org.gbif.pipelines.io.avro.Validation.Builder newBuilder(org.gbif.pipelines.io.avro.Validation.Builder other) {
    return new org.gbif.pipelines.io.avro.Validation.Builder(other);
  }
  
  /** Creates a new Validation RecordBuilder by copying an existing Validation instance */
  public static org.gbif.pipelines.io.avro.Validation.Builder newBuilder(org.gbif.pipelines.io.avro.Validation other) {
    return new org.gbif.pipelines.io.avro.Validation.Builder(other);
  }
  
  /**
   * RecordBuilder for Validation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Validation>
    implements org.apache.avro.data.RecordBuilder<Validation> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence severity;

    /** Creates a new Builder */
    private Builder() {
      super(org.gbif.pipelines.io.avro.Validation.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.gbif.pipelines.io.avro.Validation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.severity)) {
        this.severity = data().deepCopy(fields()[1].schema(), other.severity);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Validation instance */
    private Builder(org.gbif.pipelines.io.avro.Validation other) {
            super(org.gbif.pipelines.io.avro.Validation.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.severity)) {
        this.severity = data().deepCopy(fields()[1].schema(), other.severity);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public org.gbif.pipelines.io.avro.Validation.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public org.gbif.pipelines.io.avro.Validation.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'severity' field */
    public java.lang.CharSequence getSeverity() {
      return severity;
    }
    
    /** Sets the value of the 'severity' field */
    public org.gbif.pipelines.io.avro.Validation.Builder setSeverity(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.severity = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'severity' field has been set */
    public boolean hasSeverity() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'severity' field */
    public org.gbif.pipelines.io.avro.Validation.Builder clearSeverity() {
      severity = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Validation build() {
      try {
        Validation record = new Validation();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.severity = fieldSetFlags()[1] ? this.severity : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
