package org.gbif.dwca.generator.util;

import org.gbif.dwca.DwCATerm;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * This is data model generated by {@link DwCAHTMLParsingTool}. This model is used to create DwCA
 * schema.
 *
 * @author clf358
 */
public class DwCADataModel {

  private final List<DwCATerm> categories = new ArrayList<>();
  private final Map<String, DwCATerm> identifierCategoryMap = new HashMap<>();
  private final Map<String, List<DwCATerm>> categoryIdentifierAndFieldsMap = new HashMap<>();
  private final List<DwCATerm> listOfAllTerms = new ArrayList<>();

  /**
   * @return categories present in model
   */
  public List<DwCATerm> getCategories() {
    return categories;
  }

  /**
   * @return get map of category identifier and Category term information
   */
  public Map<String, DwCATerm> getIdentifierCategoryMap() {
    return identifierCategoryMap;
  }

  /**
   * @return get map of category identifier as key and all possible associated fields(associated
   * terms) as values.
   */
  public Map<String, List<DwCATerm>> getCategoryIdentifierAndFieldsMap() {
    return categoryIdentifierAndFieldsMap;
  }

  /**
   * @return list of all terms defined in the DwCA Spec
   */
  public List<DwCATerm> getListOfAllTerms() {
    return listOfAllTerms;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append("DwCADataModel [categories=")
      .append(categories)
      .append("\n, identifierCategoryMap=")
      .append(identifierCategoryMap)
      .append("\n, categoryIdentifierAndFieldsMap=")
      .append(categoryIdentifierAndFieldsMap)
      .append("\n, listOfAllTerms=")
      .append(listOfAllTerms)
      .append("]");
    return builder.toString();
  }

}
